### ISSUE TITLE
Support for general cards

### ISSUE THREAD

**Issue by Airon90** [brarcher/gift-card-guard#9]
Is it possible to extend support not only to gift card but also to general cards (i.e. supermarket cards)?

- They don't need values as they don't store money but they would need optionally values for points
- Instead of take picture of the card, the app should show the generated barcode with max backlight:
    - [Here](http://www.onbarcode.com/products/java_barcode/) is a guide on how to manage bar codes in Java
    - I tested some cards with my bar code and I found out that the bar code format is [UPC_A](http://www.onbarcode.com/products/java_barcode/barcodes/upca.html)
    - It should show the card ID too

**Comment by brarcher** [comment]
Thanks for your interest in the project.

I'm not sure I understand what you mean by supermarket cards. Are they loyalty cards that have points based on purchases? Is there a reason this information needs to be independently stored outside of the supermarket's databases?

This project was born from my frustration with buying gift cards, but sometimes not being able to spend all of the money on the card before the card stopped working and I was left with no proof of the card's value. The hope was that by being able to keep a picture of the most recent receipt along with information on the gift card I will be able to argue with a store next time it happens and be able to use the gift card for its full amount.

If there is a similar issue with general cards, then maybe being able to store them using this project makes sense. Otherwise, can you describe the use case?

**Comment by airon90** [comment]
Thank you for your answer! I try to explain the reason of this bug in order to clear my intention:

First of all, thank you for telling me that the correct name of this kind of cards is "loyalty card" :D

This request is born from my frustration with having many (maaany) loyalty cards but not carrying them with me when I go to supermarket so I never use them. I need an app that shows bar code of my cards in order to be read by optical reader at supermarket when buying something. It can be useful to manually keep the value of the points up to date, too. 

I looked for a free software app that at least shows bar codes of my cards but I never found it on Android. There is a [similar app](https://marketplace.firefox.com/app/cardstorage) on Firefox OS but can't be installed on Android. Yesterday I discovered Gift Card Guard on F-Droid so I - first of all - translated it into Italian, as I'm not a coder so I help contributing to free software programs in this way, and then created this feature request, hoping that my wish comes true ;)

I think that it is possible to combine both features in one app that manage cards but some changes are required, i.e. name of the app. Otherwise, another app for loyaly cards can be created by forking GCG (but I'm not a coder and I desperately need this app). 

I wait for your response :)

**Comment by brarcher** [comment]
I took a look at the Cardstorage program for Firefox OS, as well as a library for [zxing](https://github.com/zxing/zxing) library for scanning barcodes. Probably at this time I'll not pursue creating such an application. My goal thus far has been to get enough knowledge and experience to finish my [budget-watch](https://github.com/brarcher/budget-watch) application. Perhaps after that application is finished (maybe in a few weeks) I may circle back and take a look at the Cardstorage application.

**Comment by SecUpwN** [comment]
Thanks @Airon90 for filing this Issue, I just wanted to file exactly what you just said. @brarcher, a great example for what we would like to see implemented in your app is [Stocard](http://stocardapp.com/). Good to know you're on it!

**Comment by brarcher** [comment]
So it seems that there is more interest in such an application. (:

@SecUpwN looking at Stocard (but not actually downloading it, so I may be wrong) it appears it will simply let one scan a number of loyalty cards, show them in a list, and when selected display a barcode. Does the app do anything else that is useful?

I am wondering how the application gets the icons for the various businesses. Perhaps all possible icons it could display are baked in, or maybe it searches for them somehow then downloads them? The app's webpage says it supports up to 1800 cards, so maybe they are baked in.

**Comment by SecUpwN** [comment]
> Does the app do anything else that is useful?

Kind of. It lets you manually add a card when scanning it fails by simply typing the barcode number into it and selecting a custom Icon for the card. Other than that, Stocard makes its money by displaying ads from the cards the user has entered - which I find a rather annoying "feature". So please don't add that.

> I am wondering how the application gets the icons for the various businesses. Perhaps all possible icons it could display are baked in, or maybe it searches for them somehow then downloads them? The app's webpage says it supports up to 1800 cards, so maybe they are baked in.

They are baked in. When starting that app, the user can first select the country and then certains sets are loaded. I recommend you to try the app just once to find out which features it has that can be added here.

**Comment by brarcher** [comment]
@Airon90  @SecUpwN See if the following is close to what you are thinking:
[Loyalty Card Locker](https://github.com/brarcher/loyalty-card-locker)

You will find that it looks remarkably like the Gift Card Guard application. Maybe that is OK for now.

Decompiling Stocard I find that it contains all the icons for all the companies it supports, as well as a database mapping which cards to display for what countries. While that would be easy enough to duplicate, for now I will avoid doing so.

**Comment by SecUpwN** [comment]
> See if the following is close to what you are thinking: [Loyalty Card Locker](https://github.com/brarcher/loyalty-card-locker)

Yeeehaww, that looks like the app I wanted to have! But somehow my camera app refuses to work there.

> You will find that it looks remarkably like the Gift Card Guard application. Maybe that is OK for now.

Of course it would be, but I cannot scan gift cards since my camera app does not like your app.

> Decompiling Stocard I find that it contains all the icons for all the companies it supports, as well as a database mapping which cards to display for what countries. While that would be easy enough to duplicate, for now I will avoid doing so.

Thanks, that'll be OK for now. I'll now head over to the other repo and give it a star. ;-)
